volumes:
  user_uploads:
  wooey_db:

services:
  wooey:
    extends:
      file: docker-compose.common.yml
      service: common
    ports:
      - 10000:8080
    depends_on:
      - rabbit
      - redis
      - db
      - celery
    command: ./run-server
    restart: always

  celery:
    extends:
      file: docker-compose.common.yml
      service: common
    depends_on:
      - rabbit
      - redis
      - db
    command: watchmedo auto-restart --directory=$BUILD_DIR/wooey --recursive --ignore-patterns="*.pyc" -- celery -A $WOOEY_PROJECT worker -c 1 -B -l debug -s schedule
    restart: always
  rabbit:
    image: rabbitmq:3.9.29-management-alpine
    ports:
      - 15672:15672
    volumes:
      - wooey_db:/var/lib/postgresql/data
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    # command: rabbitmqctl eval 'application:set_env(rabbit,consumer_timeout,172800000).'
    restart: always
  db:
    image: postgres:13.10
    volumes:
      - wooey_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wooey
      POSTGRES_PASSWORD: wooey
      POSTGRES_DB: wooey
    restart: always
  redis:
    image: redis:7.2.3
    restart: always
